### ISSUE TITLE
Support retrieving job console output

### ISSUE THREAD

**Issue by vloth** [m-sureshraj/jenni#42]
Hello!
First off, thanks for developing this tool, my workflow is much better with it!
To maximize my experience in terminal one feature I'm missing is to be able to get the job console output from jenni.
That's my primarily way of debugging when a job fails.
Would you be interest in a pull request to add this feature?

**Comment by m-sureshraj** [comment]
Hi @vloth,

> my workflow is much better with it!

Fantastic! I'm happy to hear that.

> Would you be interested in a pull request to add this feature?

Yes. Feel free to work on this. It would be great if you can post the proposed API here for the discussion.

**Comment by m-sureshraj** [comment]
You can use this Jenkins API `${BUILD_URL}/consoleText` to fetch build console output.

**Comment by vloth** [comment]
That's the api I was planning to use
