### ISSUE TITLE
console command should provide a option to view the running build console output

### ISSUE THREAD

**Issue by m-sureshraj** [m-sureshraj/jenni#51]
![image](https://user-images.githubusercontent.com/12813750/87551461-08b71400-c6ce-11ea-8ad4-4503ce439805.png)

**Comment by vloth** [comment]
Looks good to me! I just have one small question:
Do you think maybe the same behavior should be applied to watching builds? (it might be a bit trickier, as it's also triggering builds now)

**Comment by m-sureshraj** [comment]
Hello Vloth,

> Do you think maybe the same behavior should be applied to watching builds?

What do you mean by **watching builds**? Are you referring to the `jen build` command?

#### `jen build` command behavior

This command used to trigger a new build. It asks user confirmation if the job has running builds before triggering a new build. Optionally it takes an argument `--watch` to progressively print the triggered build's console output. 

I think for a long-running build, it's not practical to continuously watch a running build (btw it's possible with a separate terminal tab). Instead, we can use the `jen console` command periodically to watch the latest console output of a running build.

**Comment by vloth** [comment]
Got it! seems good to me! 👍
