### ISSUE TITLE
OrganizationFolder job type not supported

### ISSUE THREAD

**Issue by bn3t** [m-sureshraj/jenni#61]
I would like to use Jenni but

    ❯ jen status                                                     
    Unsupported job type: OrganizationFolder

Thank you for your help

**Comment by m-sureshraj** [comment]
Hi @bn3t, 
Thank you for reporting the issue.

At the moment Jenni handles only `WorkflowJob` and `WorkflowMultiBranchProject` job types. https://github.com/m-sureshraj/jenni#known-limitations

I haven't tested Jenni on the `OrganizationFolder` job type yet. But I think we can easily support this job type as well.

**Comment by m-sureshraj** [comment]
Hello @bn3t,

I've created a PR to handle jobs that are inside the `OrganizationFolder` when initializing Jenni. And I've tested it on a Bitbucket project, and it works fine. If possible, could you check the feature locally? Thanks.

**Comment by bn3t** [comment]
Hi,

I have run from the branch folder of the Jenni project using:

    node ./src/bin/jen.js init  

It made the connection alright now, when it was failing before.

I don't know how to use the status command to do further tests. If I run the status command from the folder where the Jenni project is clone, it does not work because this branch does not exist on my Jenkins.

I would say the init command worked fine so maybe it's proof enough that the other commands would work as well.

Thanks for making this change.

**Comment by m-sureshraj** [comment]
Hello,

> If I run the status command from the folder where the Jenni project is cloned, it does not work because this branch does not exist on my Jenkins.

No, you can't use Jenni (cloned project) itself to test its features. Please follow the below steps when testing Jenni.

```
// uninstall previously installed package
> npm uninstall -g jenni

// clone the project
> git clone git@github.com:m-sureshraj/jenni.git

// switch to the feature branch 
> git fetch origin
> git checkout support-org-folder 

> npm link

// Now, switch to your Jenkins project & initialize the Jenni
> jen init

> jen status
```

Thanks.

**Comment by bn3t** [comment]
Thanks for all the details for testing locally, very helpful.

jen init worked fined and I can run status on branches like `develop`. Probably an other problem but if the branch name is like `feature/whatever`, I can an error message like the following:

    $ # In feature branch: feature/whatever:
    $ jen status
    Job not found - Jenkins job does not exist for branch "whatever"

**Comment by m-sureshraj** [comment]
> jen init worked fined and I can run status on branches like develop.

That's great.

> Probably another problem

Indeed. I think it's a general bug on Jenni, not specific to the organization folder. I never used slashes when naming git branches. And I didn't get a chance to test Jenni on a branch that has slashes in its name. I will create a sperate issue to handle this scenario.

Thanks for the support @bn3t

**Comment by bn3t** [comment]
> > jen init worked fined and I can run status on branches like develop.
> 
> That's great.
> 
> > Probably another problem
> 
> Indeed. I think it's a general bug on Jenni, not specific to the organization folder. I never used slashes when naming git branches. And I didn't get a chance to test Jenni on a branch that has slashes in its name. I will create a sperate issue to handle this scenario.
> 
> Thanks for the support @bn3t

Such branches names are common in the git flow scheme, it would be great if you could add support for that. The tool seems promising, I am looking forward to be able to use it!

**Comment by m-sureshraj** [comment]
> it would be great if you could add support for that

Will resolve it soon. I've already created a ticket to handle this scenario. https://github.com/m-sureshraj/jenni/issues/63
